# Dockerfile generated by GeneXus (Java)
FROM tomcat:10.1.7-jdk17-temurin-jammy
LABEL maintainer="eudavalos <eudavalos91@gmail.com>"
WORKDIR /usr/local/tomcat/webapps/
COPY tomcat/bin/setenv.sh /usr/local/tomcat/bin
RUN [ -d ROOT/ ] && mv ROOT/ ROOT.old/ || true
ADD ["ROOT.war", "/usr/local/tomcat/webapps/"]
