# Dockerfile generated by GeneXus (Java)
FROM tomcat:10-jdk15-openjdk-oracle
LABEL maintainer="EuDavalos <EuDavalos@example.com>"
WORKDIR /usr/local/tomcat/webapps/
RUN [ -d ROOT/ ] && mv ROOT/ ROOT.old/ || true
ADD ["ROOT.war", "/usr/local/tomcat/webapps/"]
