# Dockerfile generated by GeneXus (Java)
FROM tomcat:9.0.58-jdk1.8.0_311
LABEL maintainer="eudavalos <eudavalos91@gmail.com>"
WORKDIR /usr/local/tomcat/webapps/
COPY tomcat/bin/setenv.sh /usr/local/tomcat/bin
RUN [ -d ROOT/ ] && mv ROOT/ ROOT.old/ || true
ADD ["mystore.war", "/usr/local/tomcat/webapps/"]
